### ISSUE TITLE
Ideas for next version

### ISSUE THREAD

**Issue by JJ** [mariosky/splash-volunteer#1]
Change the server to include a limited and configurable cache and make three tests:
1. Using node clients in a single or several machines.
2. Using just volunteer clients in a server
3. Using both.

I think that would be enough to prove that it is useful as a supplement to regular parallel computing. What do you think, @mariosky ?

**Comment by mariosky** [comment]
On Wed, Feb 24, 2016 at 11:26 PM, Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> Change the server to include a limited and configurable cache and make
> three tests:
> 1. Using node clients in a single or several machines.
> 2. Using just volunteer clients in a server
> 3. Using both.
> 
> I think that would be enough to prove that it is useful as a supplement to
> regular parallel computing. What do you think, @mariosky
> https://github.com/mariosky ?

 Ok, I can work on this next week.

The problem? Difficult Rastrign or OneMax?

**Comment by JJ** [comment]
Difficult Rastrigin. For the time being I would have to change the server.
